services:
  - name: laravel-app
    type: web
    env: docker
    plan: free
    repo: https://github.com/SpyHolder/Angkatan24.git  # Ganti dengan repo kamu
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql12.freesqldatabase.com
      - key: DB_DATABASE
        value: sql12770756
      - key: DB_USERNAME
        value: sql12770756
      - key: DB_PASSWORD
        value: MXsu4jQnAE
